server:
  port: 8000

spring:
  application:
    name: User

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:8080/usersDB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: debug
    org.hibernate.SQL: DEBUG

