server:
  port: 8001

spring:
  application:
    name: chat

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:8081/chatsDB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: debug
    org.hibernate.SQL: DEBUG

